create extension if not exists pgcrypto with schema extensions;

create type public.knowledge_record_type as enum (
  'KNOWLEDGE',
  'EXPERIENCE'
);

create type public.knowledge_record_status as enum (
  'CANDIDATE',
  'PUBLISHED',
  'SUPERSEDED',
  'RETRACTED',
  'CONFLICTED'
);

create type public.knowledge_privacy_status as enum (
  'UNASSESSED',
  'PASS',
  'FAIL'
);

create type public.knowledge_source_type as enum (
  'PUBLIC_GPT'
);

create type public.experience_maturity as enum (
  'OBSERVED',
  'REPEATED',
  'SUPPORTED',
  'ESTABLISHED_PATTERN'
);

create type public.knowledge_record_event_type as enum (
  'CREATED',
  'OBSERVATION_ADDED',
  'MATURITY_CHANGED',
  'PUBLISHED',
  'SUPERSEDED',
  'RETRACTED',
  'CONFLICTED'
);

create table public.records (
  id uuid primary key default gen_random_uuid(),
  record_type public.knowledge_record_type not null,
  title text not null check (char_length(btrim(title)) between 3 and 200),
  component text not null check (char_length(btrim(component)) between 1 and 100),
  content text not null check (char_length(btrim(content)) between 3 and 8000),
  applicability text not null check (char_length(btrim(applicability)) between 3 and 2000),
  status public.knowledge_record_status not null default 'CANDIDATE',
  privacy_status public.knowledge_privacy_status not null default 'UNASSESSED',
  maturity public.experience_maturity,
  provenance jsonb not null default '{}'::jsonb check (jsonb_typeof(provenance) = 'object'),
  raw_evidence_included boolean not null default false,
  sanitized boolean not null default false,
  generalized boolean not null default false,
  published_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint records_experience_maturity_check check (
    (record_type = 'EXPERIENCE' and maturity is not null)
    or (record_type = 'KNOWLEDGE' and maturity is null)
  ),
  constraint records_published_timestamp_check check (
    (status = 'PUBLISHED' and published_at is not null)
    or status <> 'PUBLISHED'
  )
);

create table public.observations (
  id uuid primary key default gen_random_uuid(),
  record_id uuid not null references public.records(id) on delete restrict,
  content text not null check (char_length(btrim(content)) between 3 and 8000),
  source_type public.knowledge_source_type not null,
  validated boolean not null,
  independent boolean not null,
  privacy_status public.knowledge_privacy_status not null,
  raw_evidence_included boolean not null default false,
  sanitized boolean not null default false,
  generalized boolean not null default false,
  created_at timestamptz not null default now()
);

create table public.record_events (
  id bigint generated by default as identity primary key,
  record_id uuid not null references public.records(id) on delete restrict,
  observation_id uuid references public.observations(id) on delete restrict,
  event_type public.knowledge_record_event_type not null,
  old_maturity public.experience_maturity,
  new_maturity public.experience_maturity,
  actor_source_type public.knowledge_source_type,
  details jsonb not null default '{}'::jsonb check (jsonb_typeof(details) = 'object'),
  created_at timestamptz not null default now()
);

create index records_public_visibility_idx
  on public.records (status, privacy_status, updated_at desc);

create index records_component_idx
  on public.records (component);

create index observations_record_created_idx
  on public.observations (record_id, created_at desc);

create index record_events_record_created_idx
  on public.record_events (record_id, created_at, id);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  new.updated_at := now();
  return new;
end;
$$;

create trigger records_set_updated_at
before update on public.records
for each row execute function public.set_updated_at();

create or replace function public.reject_record_event_mutation()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  raise exception using errcode = '42501', message = 'record_events is append-only';
end;
$$;

create trigger record_events_reject_mutation
before update or delete on public.record_events
for each row execute function public.reject_record_event_mutation();

alter table public.records enable row level security;
alter table public.observations enable row level security;
alter table public.record_events enable row level security;

revoke all on table public.records from public, anon, authenticated, service_role;
revoke all on table public.observations from public, anon, authenticated, service_role;
revoke all on table public.record_events from public, anon, authenticated, service_role;
revoke all on sequence public.record_events_id_seq from public, anon, authenticated, service_role;
revoke execute on function public.set_updated_at() from public, anon, authenticated, service_role;
revoke execute on function public.reject_record_event_mutation() from public, anon, authenticated, service_role;
